version: '3'
services:
            user:
                        build:
                                    context: ./packages/server/services/user
                                    dockerfile: Dockerfile.dev
                        ports:
                                    - '7000:7000'
                        volumes:
                                    - ./packages/server/services/user:/usr/app
                        depends_on:
                                    - database
                        environment:
                                    DATABASE_CONNECTION_STRING: 'mongodb://root:example@database:27017'
                                    NODE_ENV: 'development'
                                    PORT: 7000
                                    WAIT_HOSTS: database:27017
            post:
                        build:
                                    context: ./packages/server/services/post
                                    dockerfile: Dockerfile.dev
                        ports:
                                    - '7001:7000'
                        volumes:
                                    - ./packages/server/services/post:/usr/app
                        environment:
                                    PORT: 7000
            nginx:
                        build:
                                    context: ./packages/nginx
                                    dockerfile: Dockerfile.dev
                        ports:
                                    - 80:80
                        depends_on:
                                    - client
                                    - server
                        environment:
                                    WAIT_HOSTS: client:3000, server:4000
            client:
                        build:
                                    context: ./packages/client
                                    dockerfile: Dockerfile.dev
                        ports:
                                    - 3000:3000
                        volumes:
                                    - /usr/app/node_modules
                                    - ./packages/client:/usr/app
                        depends_on:
                                    - server
                        restart: always
                        environment:
                                    REACT_APP_SERVER_PORT: 4000
            server:
                        # build:
                        #             context: ./packages/server
                        #             dockerfile: Dockerfile.dev
                        image: mandevicesiot/mandevice-server-dev
                        ports:
                                    - '4000:4000'
                        volumes:
                                    - /usr/app/node_modules
                                    - ./packages/server:/usr/app
                        depends_on:
                                    - user
                                    - post
                        restart: always
                        environment:
                                    PORT: 4000
                                    WAIT_HOSTS: user:7000, post:7000
            database:
                        ports:
                                    - '27017:27017'
                        image: mongo
                        restart: always
                        environment:
                                    MONGO_INITDB_ROOT_USERNAME: root
                                    MONGO_INITDB_ROOT_PASSWORD: example

            mongo-express:
                        image: mongo-express
                        restart: always
                        depends_on:
                                    - server
                        ports:
                                    - 8081:8081
                        environment:
                                    ME_CONFIG_MONGODB_SERVER: database
                                    ME_CONFIG_MONGODB_ADMINUSERNAME: root
                                    ME_CONFIG_MONGODB_ADMINPASSWORD: example
