version: '3'
services:
            user:
                        build:
                                    context: ./server/services/user
                                    dockerfile: Dockerfile.dev
                        ports:
                                    - '7000:7000'
                        volumes:
                                    - ./server/services/user:/usr/app
                        depends_on:
                                    - database
                        environment:
                                    PORT: 7000
                                    WAIT_HOSTS: database:27017
            post:
                        build:
                                    context: ./server/services/post
                                    dockerfile: Dockerfile.dev
                        ports:
                                    - '7001:7000'
                        volumes:
                                    - ./server/services/post:/usr/app
                        environment:
                                    PORT: 7000
            nginx:
                        build:
                                    context: ./nginx
                                    dockerfile: Dockerfile.dev
                        ports:
                                    - 80:80
                        environment:
                                    WAIT_HOSTS: client:3000, server:4000
                        depends_on:
                                    - client
                                    - server
            client:
                        build:
                                    context: ./client
                                    dockerfile: Dockerfile.dev
                        ports:
                                    - 3000:3000
                        depends_on:
                                    - server
                        volumes:
                                    - ./client:/usr/app
                        environment:
                                    REACT_APP_SERVER_PORT: 4000
                        restart: always
            server:
                        build:
                                    context: ./server
                                    dockerfile: Dockerfile.dev
                        ports:
                                    - '4000:4000'
                        volumes:
                                    - ./server:/usr/app
                        depends_on:
                                    - user
                                    - post
                        environment:
                                    PORT: 4000
                                    WAIT_HOSTS: user:7000, post:7000
                        restart: always
            database:
                        image: mongo
                        restart: always
                        ports:
                                    - '27017:27017'
                        environment:
                                    MONGO_INITDB_ROOT_USERNAME: root
                                    MONGO_INITDB_ROOT_PASSWORD: example

            mongo-express:
                        image: mongo-express
                        restart: always
                        ports:
                                    - 8081:8081
                        depends_on:
                                    - server
                        environment:
                                    ME_CONFIG_MONGODB_SERVER: database
                                    ME_CONFIG_MONGODB_ADMINUSERNAME: root
                                    ME_CONFIG_MONGODB_ADMINPASSWORD: example
